### ISSUE TITLE
Build UI for DrumKit music generation mode

### ISSUE THREAD

**Issue by alexfjw** [pyxyyy/gesture-drumkit#16]
### Requirements

**Control Panel**
Tempo control | Playback control | Clear
(up, down) | (play, pause, record) 

**Rows of instruments**
Row: Instrument name | 16 grey boxes 
Clear should clear the currently selected row
....

Tempo varies from 60-120
Line moves at 1 grey box per second for tempo = 60

![image](https://user-images.githubusercontent.com/11351531/55057945-9f109200-50a5-11e9-94e5-be2a1f06bae4.png)

**TODO**: 
- [x] control panel
- [x] timing line
- [x] instrument row
- [x] combining rows & timing line into 1 view object
- [x] move seekbar when recording/playing
- [x] add row selection ui & clear logic
- [ ] snap seekbar to start of nearest beat if record/play is clicked

**Comment by alexfjw** [comment]
Looks like this for now, left with checking the length of the boxes & moving the timing line.

![Screenshot_1554352205](https://user-images.githubusercontent.com/11351531/55529753-73109480-56d5-11e9-81af-a3468fc89e77.png)

**Comment by senyuuri** [comment]
Looks amazing!

**Comment by alexfjw** [comment]
Note that the movement of the seekbar will not be 100% accurate, since we added a bit of extra padding between every 4 beats.

Here's a video I can't figure out how to rotate (webm isn't friendly):
https://drive.google.com/file/d/14YReV8OjsjKTIJEXe_QynUYebISmANvv/view?usp=sharing
